import type { GenerationEventType } from '$lib/events/generation/GenerationEventRegistry';

export const TIMER_EVENTS = {
  KEYBOARD_KEY_DOWN: 'timer.input.keyboard-key-down',
  KEYBOARD_KEY_UP: 'timer.input.keyboard-key-up',
  MANUAL_TIME_SUBMITTED: 'timer.input.manual-time-submitted',
  VIRTUAL_MOVE_RECEIVED: 'timer.input.virtual-move-received',
  DEVICE_PREVENTION_ENTERED: 'timer.device.prevention-entered',
  DEVICE_READY: 'timer.device.ready',
  DEVICE_INSPECTION_STARTED: 'timer.device.inspection-started',
  DEVICE_GREEN_LIGHT_CHANGED: 'timer.device.green-light-changed',
  DEVICE_RUN_STARTED: 'timer.device.run-started',
  DEVICE_RUN_STOPPED: 'timer.device.run-stopped',
  DEVICE_RUN_CANCELLED: 'timer.device.run-cancelled',
  DEVICE_PAUSED: 'timer.device.paused',
  DEVICE_RESUMED: 'timer.device.resumed',
  DEVICE_STEP_COMPLETED: 'timer.device.step-completed',
  DEVICE_PENALTY_APPLIED: 'timer.device.penalty-applied',
  DEVICE_DISCOVERY_REQUESTED: 'timer.device.discovery-requested',
  DEVICE_DISCOVERED: 'timer.device.discovered',
  DEVICE_CONNECTED: 'timer.device.connected',
  DEVICE_DISCONNECTED: 'timer.device.disconnected',
  ACTIVE_DEVICE_CHANGE_REQUESTED: 'timer.device.active-change-requested',
  ACTIVE_DEVICE_CHANGED: 'timer.device.active-changed',
  ACTIVE_DEVICE_CHANGE_REJECTED: 'timer.device.active-change-rejected',
  ACTIVE_DEVICE_RELEASE_REQUESTED: 'timer.device.active-release-requested',
  ACTIVE_DEVICE_RELEASED: 'timer.device.active-released',
  ACTIVE_DEVICE_RELEASE_REJECTED: 'timer.device.active-release-rejected',
  DEVICE_DISCONNECT_REQUESTED: 'timer.device.disconnect-requested',
  DEVICE_DISCONNECT_FAILED: 'timer.device.disconnect-failed',
  DEVICE_CATALOG_UPDATED: 'timer.device.catalog-updated',
  LEGACY_DEVICE_CATALOG_SYNC_REQUESTED: 'timer.device.legacy-catalog-sync-requested',
  DEVICE_OWNER_DESTROY_REQUESTED: 'timer.device.owner-destroy-requested',
  SESSION_SWITCH_REQUESTED: 'timer.session.switch-requested',
  SESSION_SWITCHED: 'timer.session.switched',
  SESSION_SETTINGS_CHANGE_REQUESTED: 'timer.session.settings-change-requested',
  SESSION_SETTINGS_CHANGED: 'timer.session.settings-changed',
  SOLVES_LIST_REQUESTED: 'timer.solve.list-requested',
  SOLVES_LIST_LOADED: 'timer.solve.list-loaded',
  SOLVE_ADD_REQUESTED: 'timer.solve.add-requested',
  SOLVE_ADDED: 'timer.solve.added',
  SOLVE_UPDATE_REQUESTED: 'timer.solve.update-requested',
  SOLVE_UPDATED: 'timer.solve.updated',
  SOLVES_REMOVE_REQUESTED: 'timer.solve.remove-requested',
  SOLVES_REMOVED: 'timer.solve.removed',
  SCRAMBLE_REQUESTED: 'timer.scramble.requested',
  SCRAMBLE_GENERATED: 'timer.scramble.generated',
  SCRAMBLE_GENERATION_FAILED: 'timer.scramble.generation-failed',
  SCRAMBLE_PREVIEW_REQUESTED: 'timer.scramble-preview.requested',
  SCRAMBLE_PREVIEW_GENERATED: 'timer.scramble-preview.generated',
  SCRAMBLE_PREVIEW_GENERATION_FAILED: 'timer.scramble-preview.generation-failed',
  SCRAMBLE_PREVIEW_CLEARED: 'timer.scramble-preview.cleared',
  STATISTICS_REQUESTED: 'timer.statistics.requested',
  STATISTICS_UPDATED: 'timer.statistics.updated',
  NEW_RECORD: 'timer.statistics.new-record',
  HANDLER_FAILED: 'timer.system.handler-failed',
} as const;

export type TimerEventType =
  | (typeof TIMER_EVENTS)[keyof typeof TIMER_EVENTS]
  | GenerationEventType;
